<?php

// Composer: "fzaninotto/faker": "v1.3.0"
use Faker\Factory as Faker;

class NationalitieTableSeeder extends Seeder {

	public function run()
	{
		$faker = Faker::create();
		Nationalitie::create([ 'id' => "2",'name'   => 'AFGANISTÁN']);
        Nationalitie::create([ 'id' => "5",'name'   => 'ALBANIA']);
        Nationalitie::create([ 'id' => "59",'name'   => 'ALEMANIA']);
        Nationalitie::create([ 'id' => "6",'name'   => 'ANDORRA']);
        Nationalitie::create([ 'id' => "3",'name'   => 'ANGOLA']);
        Nationalitie::create([ 'id' => "4",'name'   => 'ANGUILA']);
        Nationalitie::create([ 'id' => "12",'name'   => 'ANTÁRTIDA']);
        Nationalitie::create([ 'id' => "14",'name'   => 'ANTIGUA Y BARBUDA']);
        Nationalitie::create([ 'id' => "7",'name'   => 'ANTILLAS NEERLANDESAS']);
        Nationalitie::create([ 'id' => "188",'name'   => 'ARABIA SAUDITA']);
        Nationalitie::create([ 'id' => "64",'name'   => 'ARGELIA']);
        Nationalitie::create([ 'id' => "9",'name'   => 'ARGENTINA']);
        Nationalitie::create([ 'id' => "10",'name'   => 'ARMENIA']);
        Nationalitie::create([ 'id' => "1",'name'   => 'ARUBA']);
        Nationalitie::create([ 'id' => "15",'name'   => 'AUSTRALIA']);
        Nationalitie::create([ 'id' => "16",'name'   => 'AUSTRIA']);
        Nationalitie::create([ 'id' => "17",'name'   => 'AZERBAIYÁN']);
        Nationalitie::create([ 'id' => "25",'name'   => 'BAHAMAS']);
        Nationalitie::create([ 'id' => "24",'name'   => 'BAHREIN']);
        Nationalitie::create([ 'id' => "22",'name'   => 'BANGLADESH']);
        Nationalitie::create([ 'id' => "32",'name'   => 'BARBADOS']);
        Nationalitie::create([ 'id' => "27",'name'   => 'BELARUS']);
        Nationalitie::create([ 'id' => "19",'name'   => 'BELGICA']);
        Nationalitie::create([ 'id' => "28",'name'   => 'BELICE']);
        Nationalitie::create([ 'id' => "20",'name'   => 'BENIN']);
        Nationalitie::create([ 'id' => "29",'name'   => 'BERMUDAS']);
        Nationalitie::create([ 'id' => "34",'name'   => 'BHUTAN']);
        Nationalitie::create([ 'id' => "35",'name'   => 'BIRMANIA']);
        Nationalitie::create([ 'id' => "30",'name'   => 'BOLIVIA']);
        Nationalitie::create([ 'id' => "26",'name'   => 'BOSNIA Y HERZEGOVINA']);
        Nationalitie::create([ 'id' => "37",'name'   => 'BOTSWANA']);
        Nationalitie::create([ 'id' => "31",'name'   => 'BRASIL']);
        Nationalitie::create([ 'id' => "33",'name'   => 'BRUNEI DARUSSALAM']);
        Nationalitie::create([ 'id' => "23",'name'   => 'BULGARIA']);
        Nationalitie::create([ 'id' => "21",'name'   => 'BURKINA FASO']);
        Nationalitie::create([ 'id' => "18",'name'   => 'BURUNDI']);
        Nationalitie::create([ 'id' => "48",'name'   => 'CABO VERDE']);
        Nationalitie::create([ 'id' => "120",'name'   => 'CAMBOYA']);
        Nationalitie::create([ 'id' => "42",'name'   => 'CAMERUN']);
        Nationalitie::create([ 'id' => "39",'name'   => 'CANADA']);
        Nationalitie::create([ 'id' => "209",'name'   => 'CHAD']);
        Nationalitie::create([ 'id' => "55",'name'   => 'CHECA, REPUBLICA']);
        Nationalitie::create([ 'id' => "50",'name'   => 'CHECOSLOVAQUIA']);
        Nationalitie::create([ 'id' => "57",'name'   => 'CHILE']);
        Nationalitie::create([ 'id' => "58",'name'   => 'CHINA']);
        Nationalitie::create([ 'id' => "54",'name'   => 'CHIPRE']);
        Nationalitie::create([ 'id' => "46",'name'   => 'COLOMBIA']);
        Nationalitie::create([ 'id' => "47",'name'   => 'COMORAS']);
        Nationalitie::create([ 'id' => "43",'name'   => 'CONGO']);
        Nationalitie::create([ 'id' => "44",'name'   => 'CONGO']);
        Nationalitie::create([ 'id' => "41",'name'   => 'COSTA DE MARFIL']);
        Nationalitie::create([ 'id' => "49",'name'   => 'COSTA RICA']);
        Nationalitie::create([ 'id' => "102",'name'   => 'CROACIA']);
        Nationalitie::create([ 'id' => "51",'name'   => 'CUBA']);
        Nationalitie::create([ 'id' => "62",'name'   => 'DINAMARCA']);
        Nationalitie::create([ 'id' => "60",'name'   => 'DJIBOUTI']);
        Nationalitie::create([ 'id' => "61",'name'   => 'DOMINICA']);
        Nationalitie::create([ 'id' => "65",'name'   => 'ECUADOR']);
        Nationalitie::create([ 'id' => "66",'name'   => 'EGIPTO']);
        Nationalitie::create([ 'id' => "196",'name'   => 'EL SALVADOR']);
        Nationalitie::create([ 'id' => "8",'name'   => 'EMIRATOS ARABES UNIDOS']);
        Nationalitie::create([ 'id' => "238",'name'   => 'ESLOVAQUIA']);
        Nationalitie::create([ 'id' => "202",'name'   => 'ESLOVAQUIA, REPÜBLICA']);
        Nationalitie::create([ 'id' => "203",'name'   => 'ESLOVENIA']);
        Nationalitie::create([ 'id' => "68",'name'   => 'ESPAÑA']);
        Nationalitie::create([ 'id' => "229",'name'   => 'ESTADO DE LA CIUDAD DEL VATICANO']);
        Nationalitie::create([ 'id' => "227",'name'   => 'ESTADOS UNIDOS']);
        Nationalitie::create([ 'id' => "69",'name'   => 'ESTONIA']);
        Nationalitie::create([ 'id' => "70",'name'   => 'ETIOPLA']);
        Nationalitie::create([ 'id' => "186",'name'   => 'FEDERACION DE RUSIA']);
        Nationalitie::create([ 'id' => "72",'name'   => 'FIJI']);
        Nationalitie::create([ 'id' => "175",'name'   => 'FILIPINAS']);
        Nationalitie::create([ 'id' => "71",'name'   => 'FINLANDIA']);
        Nationalitie::create([ 'id' => "74",'name'   => 'FRANCIA']);
        Nationalitie::create([ 'id' => "77",'name'   => 'GABON']);
        Nationalitie::create([ 'id' => "89",'name'   => 'GAMBIA']);
        Nationalitie::create([ 'id' => "84",'name'   => 'GEORGIA']);
        Nationalitie::create([ 'id' => "85",'name'   => 'GHANA']);
        Nationalitie::create([ 'id' => "86",'name'   => 'GIBRALTAR']);
        Nationalitie::create([ 'id' => "93",'name'   => 'GRANADA']);
        Nationalitie::create([ 'id' => "92",'name'   => 'GRECIA']);
        Nationalitie::create([ 'id' => "94",'name'   => 'GROENLANDIA']);
        Nationalitie::create([ 'id' => "88",'name'   => 'GUADALUPE']);
        Nationalitie::create([ 'id' => "97",'name'   => 'GUAM']);
        Nationalitie::create([ 'id' => "95",'name'   => 'GUATEMALA']);
        Nationalitie::create([ 'id' => "96",'name'   => 'GUAYANA FRANCESA']);
        Nationalitie::create([ 'id' => "87",'name'   => 'GUINEA']);
        Nationalitie::create([ 'id' => "91",'name'   => 'GUINEA ECUATORIAL']);
        Nationalitie::create([ 'id' => "90",'name'   => 'GUINEA-BISSAU']);
        Nationalitie::create([ 'id' => "98",'name'   => 'GUYANA']);
        Nationalitie::create([ 'id' => "103",'name'   => 'HAITI']);
        Nationalitie::create([ 'id' => "164",'name'   => 'HOLANDA (PALSES BAJOS, REINO UNIDO DE LOS)']);
        Nationalitie::create([ 'id' => "101",'name'   => 'HONDURAS']);
        Nationalitie::create([ 'id' => "99",'name'   => 'HONG KONG']);
        Nationalitie::create([ 'id' => "104",'name'   => 'HUNGRIA']);
        Nationalitie::create([ 'id' => "106",'name'   => 'INDIA']);
        Nationalitie::create([ 'id' => "105",'name'   => 'INDONESIA']);
        Nationalitie::create([ 'id' => "109",'name'   => 'IRAN, REPUBLICA ISLÁMICA DEL']);
        Nationalitie::create([ 'id' => "110",'name'   => 'IRAQ']);
        Nationalitie::create([ 'id' => "108",'name'   => 'IRLANDA']);
        Nationalitie::create([ 'id' => "36",'name'   => 'ISLA BOUVET']);
        Nationalitie::create([ 'id' => "52",'name'   => 'ISLA CHRISTMAS']);
        Nationalitie::create([ 'id' => "160",'name'   => 'ISLA NORFOLK']);
        Nationalitie::create([ 'id' => "111",'name'   => 'ISLANDIA']);
        Nationalitie::create([ 'id' => "53",'name'   => 'ISLAS CAIMANES']);
        Nationalitie::create([ 'id' => "40",'name'   => 'ISLAS COCOS (KEELING)']);
        Nationalitie::create([ 'id' => "45",'name'   => 'ISLAS COOK']);
        Nationalitie::create([ 'id' => "75",'name'   => 'ISLAS FEROE']);
        Nationalitie::create([ 'id' => "100",'name'   => 'ISLAS HEARD Y MCDONALD']);
        Nationalitie::create([ 'id' => "73",'name'   => 'ISLAS MALVINAS (FALKLAND)']);
        Nationalitie::create([ 'id' => "149",'name'   => 'ISLAS MARIANAS SEPTENTRIONALES']);
        Nationalitie::create([ 'id' => "143",'name'   => 'ISLAS MARSHALL']);
        Nationalitie::create([ 'id' => "225",'name'   => 'ISLAS REMOTAS MENORES DE LOS ESTADOS UNIDOS']);
        Nationalitie::create([ 'id' => "194",'name'   => 'ISLAS SALOMON']);
        Nationalitie::create([ 'id' => "193",'name'   => 'ISLAS SVALBARD Y JAN MAYEN']);
        Nationalitie::create([ 'id' => "208",'name'   => 'ISLAS TURCAS Y CAICOS']);
        Nationalitie::create([ 'id' => "233",'name'   => 'ISLAS VIRGENES (ESTADOS UNIDOS)']);
        Nationalitie::create([ 'id' => "232",'name'   => 'ISLAS VIRGENES BRITÁNICAS']);
        Nationalitie::create([ 'id' => "236",'name'   => 'ISLAS WALLIS Y FUTUNA']);
        Nationalitie::create([ 'id' => "112",'name'   => 'ISRAÉL']);
        Nationalitie::create([ 'id' => "113",'name'   => 'ITALIA']);
        Nationalitie::create([ 'id' => "128",'name'   => 'JAMAHIRIYA ARABE LIBIA']);
        Nationalitie::create([ 'id' => "114",'name'   => 'JAMAICA']);
        Nationalitie::create([ 'id' => "116",'name'   => 'JAPON']);
        Nationalitie::create([ 'id' => "115",'name'   => 'JORDANIA']);
        Nationalitie::create([ 'id' => "117",'name'   => 'KAZAJSTAN']);
        Nationalitie::create([ 'id' => "118",'name'   => 'KENYA']);
        Nationalitie::create([ 'id' => "119",'name'   => 'KIRGUISTAN']);
        Nationalitie::create([ 'id' => "121",'name'   => 'KIRIBATI']);
        Nationalitie::create([ 'id' => "124",'name'   => 'KUWÁIT']);
        Nationalitie::create([ 'id' => "132",'name'   => 'LESOTHO']);
        Nationalitie::create([ 'id' => "135",'name'   => 'LETONIA']);
        Nationalitie::create([ 'id' => "126",'name'   => 'LIBANO']);
        Nationalitie::create([ 'id' => "127",'name'   => 'LIBERIA']);
        Nationalitie::create([ 'id' => "130",'name'   => 'LIECHTENSTEIN']);
        Nationalitie::create([ 'id' => "133",'name'   => 'LITUÁNIA']);
        Nationalitie::create([ 'id' => "134",'name'   => 'LUXEMBURGO']);
        Nationalitie::create([ 'id' => "136",'name'   => 'MACAO']);
        Nationalitie::create([ 'id' => "144",'name'   => 'MACEDONIA, REPÜBLICA YUGOSLAVA DE']);
        Nationalitie::create([ 'id' => "140",'name'   => 'MADAGASCAR']);
        Nationalitie::create([ 'id' => "156",'name'   => 'MALASIA']);
        Nationalitie::create([ 'id' => "155",'name'   => 'MALAWI']);
        Nationalitie::create([ 'id' => "141",'name'   => 'MALDIVAS']);
        Nationalitie::create([ 'id' => "145",'name'   => 'MALI']);
        Nationalitie::create([ 'id' => "146",'name'   => 'MALTA']);
        Nationalitie::create([ 'id' => "137",'name'   => 'MARRUECOS']);
        Nationalitie::create([ 'id' => "153",'name'   => 'MARTINICA']);
        Nationalitie::create([ 'id' => "154",'name'   => 'MAURICIO']);
        Nationalitie::create([ 'id' => "151",'name'   => 'MAURITANIA']);
        Nationalitie::create([ 'id' => "142",'name'   => 'MÉXICO']);
        Nationalitie::create([ 'id' => "76",'name'   => 'MICRONESIA, ESTADOS FEDERADOS DE']);
        Nationalitie::create([ 'id' => "138",'name'   => 'MONACO']);
        Nationalitie::create([ 'id' => "148",'name'   => 'MONGOLIA']);
        Nationalitie::create([ 'id' => "152",'name'   => 'MONTSERRAT']);
        Nationalitie::create([ 'id' => "150",'name'   => 'MOZAMBIQUE']);
        Nationalitie::create([ 'id' => "147",'name'   => 'MYANMAR']);
        Nationalitie::create([ 'id' => "157",'name'   => 'NAMIBIA']);
        Nationalitie::create([ 'id' => "167",'name'   => 'NAURÜ']);
        Nationalitie::create([ 'id' => "166",'name'   => 'NEPAL']);
        Nationalitie::create([ 'id' => "162",'name'   => 'NICARAGUA']);
        Nationalitie::create([ 'id' => "159",'name'   => 'NIGER']);
        Nationalitie::create([ 'id' => "161",'name'   => 'NIGERIA']);
        Nationalitie::create([ 'id' => "163",'name'   => 'NIUÉ']);
        Nationalitie::create([ 'id' => "165",'name'   => 'NORUEGA']);
        Nationalitie::create([ 'id' => "158",'name'   => 'NUEVA CALEDONIA']);
        Nationalitie::create([ 'id' => "169",'name'   => 'NUEVA ZELANDIA']);
        Nationalitie::create([ 'id' => "170",'name'   => 'OMAN']);
        Nationalitie::create([ 'id' => "171",'name'   => 'PAKISTAN']);
        Nationalitie::create([ 'id' => "176",'name'   => 'PALAÜ']);
        Nationalitie::create([ 'id' => "172",'name'   => 'PANAMA']);
        Nationalitie::create([ 'id' => "177",'name'   => 'PAPÜA NUEVA GUINÉA']);
        Nationalitie::create([ 'id' => "182",'name'   => 'PARAGUAY']);
        Nationalitie::create([ 'id' => "174",'name'   => 'PERU']);
        Nationalitie::create([ 'id' => "173",'name'   => 'PITCAIRN']);
        Nationalitie::create([ 'id' => "183",'name'   => 'POLINESIA FRANCESA']);
        Nationalitie::create([ 'id' => "178",'name'   => 'POLONIA']);
        Nationalitie::create([ 'id' => "181",'name'   => 'PORTUGAL']);
        Nationalitie::create([ 'id' => "179",'name'   => 'PUERTO RICO']);
        Nationalitie::create([ 'id' => "82",'name'   => 'REINO UNIDO (CIUDADANO BRITÁNICO)']);
        Nationalitie::create([ 'id' => "83",'name'   => 'REINO UNIDO (SUBDITO BRITÁNICO)']);
        Nationalitie::create([ 'id' => "80",'name'   => 'REINO UNIDO(C. BRIT. DEL EXTRANJERO)']);
        Nationalitie::create([ 'id' => "78",'name'   => 'REINO UNIDO(C. DE DEPEN. TERRIT. BRIT.)']);
        Nationalitie::create([ 'id' => "79",'name'   => 'REINO UNIDO(C. DE NAL. BRIT. DEL EXT.)']);
        Nationalitie::create([ 'id' => "81",'name'   => 'REINO UNIDO(PERSONA BAJO PROTEC. BRIT.)']);
        Nationalitie::create([ 'id' => "207",'name'   => 'REPÜBLICA ARABE SIRIA']);
        Nationalitie::create([ 'id' => "38",'name'   => 'REPUBLICA CENTROAFRICANA']);
        Nationalitie::create([ 'id' => "123",'name'   => 'REPÜBLICA DE COREA']);
        Nationalitie::create([ 'id' => "139",'name'   => 'REPUBLICA DE MOLDOVA']);
        Nationalitie::create([ 'id' => "125",'name'   => 'REPÜBLICA DEMOCRÁTICA POPULAR LAO']);
        Nationalitie::create([ 'id' => "63",'name'   => 'REPUBLICA DOMINICANA']);
        Nationalitie::create([ 'id' => "180",'name'   => 'REPÜBLICA POPULAR DEMOCRÁTICA DE COREA']);
        Nationalitie::create([ 'id' => "222",'name'   => 'REPUBLICA UNIDA DE TANZANIA']);
        Nationalitie::create([ 'id' => "184",'name'   => 'REUNION']);
        Nationalitie::create([ 'id' => "185",'name'   => 'RUMANIA']);
        Nationalitie::create([ 'id' => "187",'name'   => 'RWANDA']);
        Nationalitie::create([ 'id' => "67",'name'   => 'SAHARAUI']);
        Nationalitie::create([ 'id' => "122",'name'   => 'SAINT KITTS Y NEVIS']);
        Nationalitie::create([ 'id' => "199",'name'   => 'SAINT PIERRE Y MIQUELON']);
        Nationalitie::create([ 'id' => "237",'name'   => 'SAMOA']);
        Nationalitie::create([ 'id' => "11",'name'   => 'SAMOA ESTADOUNIDENSE']);
        Nationalitie::create([ 'id' => "197",'name'   => 'SAN MARINO']);
        Nationalitie::create([ 'id' => "230",'name'   => 'SAN VICENTE Y LAS GRANADINAS']);
        Nationalitie::create([ 'id' => "192",'name'   => 'SANTA ELENA']);
        Nationalitie::create([ 'id' => "129",'name'   => 'SANTA LUCIA']);
        Nationalitie::create([ 'id' => "200",'name'   => 'SANTO TOME Y PRINCIPE']);
        Nationalitie::create([ 'id' => "190",'name'   => 'SENEGAL']);
        Nationalitie::create([ 'id' => "206",'name'   => 'SEYCHELLES']);
        Nationalitie::create([ 'id' => "195",'name'   => 'SIERRA LEONA']);
        Nationalitie::create([ 'id' => "191",'name'   => 'SINGAPUR']);
        Nationalitie::create([ 'id' => "198",'name'   => 'SOMALIA']);
        Nationalitie::create([ 'id' => "131",'name'   => 'SRI LANKA']);
        Nationalitie::create([ 'id' => "241",'name'   => 'SUDÁFRICA']);
        Nationalitie::create([ 'id' => "189",'name'   => 'SUDÁN']);
        Nationalitie::create([ 'id' => "204",'name'   => 'SUECIA']);
        Nationalitie::create([ 'id' => "56",'name'   => 'SUIZA']);
        Nationalitie::create([ 'id' => "201",'name'   => 'SURINAME']);
        Nationalitie::create([ 'id' => "205",'name'   => 'SWAZILANDIA']);
        Nationalitie::create([ 'id' => "211",'name'   => 'TAILANDIA']);
        Nationalitie::create([ 'id' => "221",'name'   => 'TAIWÁN, PROVINCIA DE CHINA']);
        Nationalitie::create([ 'id' => "212",'name'   => 'TAYIKISTÁN']);
        Nationalitie::create([ 'id' => "107",'name'   => 'TERRITORIO BRITÁNICO DEL OCÉANO INDICO']);
        Nationalitie::create([ 'id' => "13",'name'   => 'TERRITORIOS FRANCESES DEL SUR']);
        Nationalitie::create([ 'id' => "215",'name'   => 'TIMOR ORIENTAL']);
        Nationalitie::create([ 'id' => "210",'name'   => 'TOGO']);
        Nationalitie::create([ 'id' => "213",'name'   => 'TOKELÁU']);
        Nationalitie::create([ 'id' => "216",'name'   => 'TONGA']);
        Nationalitie::create([ 'id' => "217",'name'   => 'TRINIDAD Y TOBAGO']);
        Nationalitie::create([ 'id' => "218",'name'   => 'TUNEZ']);
        Nationalitie::create([ 'id' => "214",'name'   => 'TURKMENISTAN']);
        Nationalitie::create([ 'id' => "219",'name'   => 'TURQUIA']);
        Nationalitie::create([ 'id' => "220",'name'   => 'TUVALU']);
        Nationalitie::create([ 'id' => "224",'name'   => 'UCRANIA']);
        Nationalitie::create([ 'id' => "223",'name'   => 'UGANDA']);
        Nationalitie::create([ 'id' => "226",'name'   => 'URUGUAY']);
        Nationalitie::create([ 'id' => "228",'name'   => 'UZBEKISTAN']);
        Nationalitie::create([ 'id' => "235",'name'   => 'VANUATU']);
        Nationalitie::create([ 'id' => "231",'name'   => 'VENEZUELA']);
        Nationalitie::create([ 'id' => "234",'name'   => 'VIET NAM']);
        Nationalitie::create([ 'id' => "239",'name'   => 'YEMEN, REPUBLICA DEL']);
        Nationalitie::create([ 'id' => "240",'name'   => 'YUGOSLAVIA']);
        Nationalitie::create([ 'id' => "242",'name'   => 'ZAIRE']);
        Nationalitie::create([ 'id' => "243",'name'   => 'ZAMBIA']);
        Nationalitie::create([ 'id' => "168",'name'   => 'ZONA NEUTRAL']);


	}

}




